# Generated by Django 4.2.5 on 2023-09-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0002_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
