# Generated by Django 4.2.5 on 2023-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0003_user_biography_user_date_of_birth_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="extra_info",
            field=models.JSONField(default=dict),
        ),
    ]
