# Generated by Django 4.2.5 on 2023-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0004_user_extra_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(
                max_length=30,
                choices=(
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                ),
            ),
        ),
    ]
